name: formose_rc
channels:
  - conda-forge
dependencies:
  - python=3.11.6
  - pip=23.3
  - numpy=1.25.2
  - scipy=1.11.2
  - pandas=2.1.1
  - openpyxl=3.1.2
  - scikit-learn=1.3.1
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - notebook=7.0.6
  - pip:
    - colorcet==3.0.1
    - amici==0.19.0
    - tellurium==2.2.8
    - python-libsbml==5.20.2
    - tomli==2.0.1
    - pyrcn==0.0.17
    